### ISSUE TITLE
SingleUserOffset.x64 is different 

### ISSUE THREAD

**Issue by davidcao2000** [llccd/RDPWrapOffsetFinder#4]
I found that one of the values obtained by your tool for termsrv.dll for Windows 10 (I only tested Windows 10) is SingleUserOffset.x64
Its value is different from the value in the rdpwrap.ini version of sebaxakerhtc.

Only the most recent versions of termsrv.dll (from 10.0.19041.4239 to 10.0.19041.4355) have exactly the same data.

Earlier than version 10.0.19041.4239, the value of SingleUserOffset.x64 is different from the sebaxakerhtc version.

For example, termsrv.dll version: 10.0.19041.3636 (Win10 22H2 03-2024), with your tool, I get: SingleUserOffset.x64=182FB
But sebaxakerhtc version: SingleUserOffset.x64=11E12

For example, termsrv.dll version: 10.0.19041.789 (Win10 21H1 10-2020), with your tool, I get: SingleUserOffset.x64=8107
But sebaxakerhtc version: SingleUserOffset.x64=0CA4C

I guess only one side is right. So which side is right?

 sebaxakerhtc version:   github.com/sebaxakerhtc/rdpwrap.ini

**Comment by loyejaotdiqr47123** [comment]
> I found that one of the values obtained by your tool for termsrv.dll for Windows 10 (I only tested Windows 10) is SingleUserOffset.x64 Its value is different from the value in the rdpwrap.ini version of sebaxakerhtc.
> 
> Only the most recent versions of termsrv.dll (from 10.0.19041.4239 to 10.0.19041.4355) have exactly the same data.
> 
> Earlier than version 10.0.19041.4239, the value of SingleUserOffset.x64 is different from the sebaxakerhtc version.
> 
> For example, termsrv.dll version: 10.0.19041.3636 (Win10 22H2 03-2024), with your tool, I get: SingleUserOffset.x64=182FB But sebaxakerhtc version: SingleUserOffset.x64=11E12
> 
> For example, termsrv.dll version: 10.0.19041.789 (Win10 21H1 10-2020), with your tool, I get: SingleUserOffset.x64=8107 But sebaxakerhtc version: SingleUserOffset.x64=0CA4C
> 
> I guess only one side is right. So which side is right?
> 
> sebaxakerhtc version: github.com/sebaxakerhtc/rdpwrap.ini

Can you upload termsrv.dll？
sebaxakerhtc is not right.

**Comment by davidcao2000** [comment]
Great! you know someone is wrong. Attached is the dll mentioned. Thanks !
[termsrv.dll.19041.3636.zip](https://github.com/llccd/RDPWrapOffsetFinder/files/15175372/termsrv.dll.19041.3636.zip)
[termsrv.dll.19041.789.zip](https://github.com/llccd/RDPWrapOffsetFinder/files/15175373/termsrv.dll.19041.789.zip)

**Comment by loyejaotdiqr47123** [comment]
Offsets have been edited
[https://github.com/sebaxakerhtc/rdpwrap.ini/commit/807f0c6cd183cf36fde65d444831b2ee5dd13eed](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/807f0c6cd183cf36fde65d444831b2ee5dd13eed)

**Comment by davidcao2000** [comment]
I noticed that in recent Windows 10 versions, the value of SingleUserOffset.x64, generated by llccdr's RDPWrapOffsetFinder, is different from sebaxakerhtc's.ini. Is the former right and the latter wrong?
I will provide more termsrv.dll version files.

**Comment by loyejaotdiqr47123** [comment]
> 我注意到在最近的 Windows 10 版本中，由 llccdr 的 RDPWrapOffsetFinder 生成的 SingleUserOffset.x64 的值与 sebaxakerhtc s.ini不同。前者是对的，后者是错的吗？我将提供更多termsrv.dll版本文件。

You're right.

**Comment by davidcao2000** [comment]
> > 我注意到在最近的 Windows 10 版本中，由 llccdr 的 RDPWrapOffsetFinder 生成的 SingleUserOffset.x64 的值与 sebaxakerhtc s.ini不同。前者是对的，后者是错的吗？我将提供更多termsrv.dll版本文件。
> 
> You're right.

这么说，有相当多的版本中， SingleUserOffset.x64 的值要按 llccdr 工具所给的值来纠正了。至少数十个。这个工作量很大。请教一下，这个SingleUserOffset.x64的用途是什么？若使用了错误值，会有什么不良结果？

**Comment by davidcao2000** [comment]
以前我用的是sebaxakerhtc的版本，如果说他的ini中的SingleUserOffset.x64是错的，但似乎也没发现有糟糕后果。

**Comment by loyejaotdiqr47123** [comment]
> 以前我用的是sebaxakerhtc的版本，如果说他的ini中的SingleUserOffset.x64是错的，但似乎也没发现有糟糕后果。

第一个登录的用户可能会被踢出而已，其他不受影响

**Comment by loyejaotdiqr47123** [comment]
这个我跟sebaxakerhtc早就在研究了

**Comment by loyejaotdiqr47123** [comment]
> > > 我注意到在最近的 Windows 10 版本中，由 llccdr 的 RDPWrapOffsetFinder 生成的 SingleUserOffset.x64 的值与 sebaxakerhtc s.ini不同。前者是对的，后者是错的吗？我将提供更多termsrv.dll版本文件。
> > 
> > 
> > You're right.
> 
> 这么说，有相当多的版本中， SingleUserOffset.x64 的值要按 llccdr 工具所给的值来纠正了。至少数十个。这个工作量很大。请教一下，这个SingleUserOffset.x64的用途是什么？若使用了错误值，会有什么不良结果？

几百个吧，从10.0.17063.1000(已知)开始都是错误的

**Comment by adream100** [comment]
几百个版本的SingleUserOffset.x64 值要修正，是否得收集这几百个版本的dll？

**Comment by loyejaotdiqr47123** [comment]
> 几百个版本的SingleUserOffset.x64 值要修正，是否得收集这几百个版本的dll？

是的

**Comment by adream100** [comment]
我去全力收集，大概有几十个。改天打个包发上来。

**Comment by loyejaotdiqr47123** [comment]
> 我去全力收集，大概有几十个。改天打个包发上来。

不需要，我这边都有

**Comment by adream100** [comment]
好的，有劳了，等待你的更新
