### ISSUE TITLE
ERROR: DefPolicyPatch patten not found on 10.0.19041.964 x64

### ISSUE THREAD

**Issue by davidcao2000** [llccd/RDPWrapOffsetFinder#6]
[10.0.19041.964]
SingleUserPatch.x64=1
SingleUserOffset.x64=8107
SingleUserCode.x64=Zero
ERROR: DefPolicyPatch patten not found

attached is the dll 
[termsrv.zip](https://github.com/llccd/RDPWrapOffsetFinder/files/15196779/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment]
@davidcao2000 
![image](https://github.com/llccd/RDPWrapOffsetFinder/assets/102934154/f5dfb297-bfa1-482f-a08b-985ca9300018)
It has been replaced.So it can't be searched

**Comment by davidcao2000** [comment]
you mean this dll is modified manually?  I found data in your ini:
[10.0.19041.964]
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx

I'm confused. can you upload an original dll?

**Comment by loyejaotdiqr47123** [comment]
![image](https://github.com/llccd/RDPWrapOffsetFinder/assets/102934154/f67f9b12-d3d3-47cb-ae88-22a4c62f8615)
Wait.I'm downloading the system.

**Comment by loyejaotdiqr47123** [comment]
[10.0.19041.964_x64.zip](https://github.com/llccd/RDPWrapOffsetFinder/files/15198547/10.0.19041.964_x64.zip)

**Comment by loyejaotdiqr47123** [comment]
```
[10.0.19041.964]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=8107
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E29C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.964-SLInit]
bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C
```

**Comment by davidcao2000** [comment]
> @davidcao2000 [10.0.19041.964_x64.zip](https://github.com/llccd/RDPWrapOffsetFinder/files/15198547/10.0.19041.964_x64.zip)

Great! your dll works normally with llccd's tool. Both of you are excellent！thanks very much.
